development:
  adapter: postgresql
  database: pcms_development
  host: ''
production:
  adapter: postgresql
  database: pcms_development
  host: ''
  username: 'root'
  password: 'password'

test:
  adapter: postgresql
  database: pcms_test
  host: ''
