development:
  adapter: postgresql
  encoding: unicode
  database: pcms_development
  pool: 5
  password: 
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: pcms_test
  pool: 5
  password:
  host: localhost
  
production:
  adapter: postgresql
